### ISSUE TITLE
🌐 [MISC] - Add workflow for welcoming the contributors

### ISSUE THREAD

**Issue by FahimFBA** [FahimFBA/python#3]
### Description

Create a relevant GitHub workflow for welcoming the contributors on the pull requests and issues. 

For reference, you can follow [this workflow](https://github.com/FahimFBA/assist-me/blob/main/.github/workflows/greetings.yml).

### Related to

Code

### Additional Information

This issue is included in Hacktoberfest. 👏

**Comment by sharp119** [comment]
can i work on this ?

**Comment by FahimFBA** [comment]
This issue has been resolved with pull request #4
