### ISSUE TITLE
🌐 [MISC] - Update README for Improved Structure and Contribution Guidelines

### ISSUE THREAD

**Issue by sharp119** [FahimFBA/python#5]
### Description

The current README of the repository lacks specific details that could make the repository more beginner-friendly and structured. Given that Python is a widely known language, many beginners can benefit from a well-structured repository that offers clear guidance on contributions and provides valuable educational content.

I propose the following updates to the README:

1. **Starter-Friendly Repo**: Highlight that this is a beginner-friendly repository, encouraging newcomers to contribute.
2. **Structured Jupyter Notebooks (ipynb)**: Emphasize the importance of well-documented Jupyter Notebooks that explain concepts like variables, loops, etc., in a clear and engaging manner.
3. **Guidelines for Standalone Python Files**: If someone wishes to contribute a standalone `.py` file, it should serve a concrete function or purpose. Additionally, the code should be well-documented and easily understandable.
4. **Encouraging Community Contributions**: While we encourage contributions, they should align with the repository's goal of being educational and beginner-friendly.

If the maintainers agree with this proposal, I recommend creating a detailed issue to further discuss the specifics of the README updates. This task can then be assigned to anyone willing to contribute.

Looking forward to the community's feedback on this!

### Related to

Documentation

### Additional Information

None for now. Open to suggestions and feedback.

**Comment by FahimFBA** [comment]
Thank you so much, @sharp119 😃 
I really like the idea. Please work on the issue if you are interested.

Let me know beforehand so that I can assign the task to you specifically, or if you want to work with others by collaboration, that is also completely fine by me!

**Comment by sharp119** [comment]
for readme part i could make it and please review it and add anything i missed or you want to add then we can merge it

**Comment by FahimFBA** [comment]
> for readme part i could make it and please review it and add anything i missed or you want to add then we can merge it

Sure! Sounds good! 👍
