### ISSUE TITLE
📘 [DOCS] - code of conduct

### ISSUE THREAD

**Issue by deepanshutyagi86** [FahimFBA/python#7]
### 📌 Type of Documentation

Guide

### 📖 Description

i would like to add code of conduct file for this repo. Can you tell me few things that are a must.

### ⚖️ Priority

🟡 Medium

### 🔍 Difficulty Level

🟢 Easy

**Comment by FahimFBA** [comment]
Thank you for the issue. For instance, you can check this [Code of Conduct](https://github.com/FahimFBA/assist-me/blob/main/CODE_OF_CONDUCT.md). Let me know if you have any more queries.
