### ISSUE TITLE
🌐 [MISC] - Add a Pull Request template

### ISSUE THREAD

**Issue by FahimFBA** [FahimFBA/python#8]
### Description

Create a workflow under the `.github` directory as a pull request template.

For instance, you can check [this](https://github.com/FahimFBA/assist-me/blob/main/.github/pull_request_template.md).

### Related to

Other

### Additional Information

This issue is beginner-friendly and Hacktoberfest 2023-accepted.

**Comment by Jaivignesh-afk** [comment]
Can i work on this?

**Comment by FahimFBA** [comment]
PR #10 closes this issue.
